### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by russelljjarvis** [dpshorten/CoTETE.jl#2]
Thanks for making this interesting package.

The install instructions are not working for me.
```
david@home:~$ git clone --recurse-submodules --branch v0.2.2 https://github.com/dpshorten/CoTETE.jl.git
make sure that CoTETE.jl/src/ is on your JULIA_LOAD_PATH. eg:

david@home:~$ export JULIA_LOAD_PATH=:/home/user/git/CoTETE.jl/src/
Fire up the Julia REPL

david@home:~$ julia
```
I wonder if it would be possible to the package to the Julia registry?

**Comment by dpshorten** [comment]
Hi Russel,

Thanks for getting in touch. Would you be able to provide me with some more information such as what OS you are using and what error messages you are receiving?

Thanks, David

**Comment by russelljjarvis** [comment]
Hi David,
.
Sorry yes. I am using Ubuntu. Actually, it was just my human error, I was supplying the wrong path to JULIA_PATH, that being said when it comes to actually applying CoTETE to real spike train data, I am encountering a different (probably human error). Maybe I can document that issue too. Thanks for your prompt reply.

Thanks,
Russell.

**Comment by dpshorten** [comment]
Hi Russell,

Yeah, it would be useful to get some insight into possible issues with the code. I'm happy to have a quick zoom chat about it if you think that will be the easiest way of resolving things.

**Comment by russelljjarvis** [comment]
I am also interested in doing a multivariate analysis on a whole network using this approach.
